import random

def toss(user_toss):
    global toss2
    comp_toss = random.randint(0,1)
    if comp_toss == user_toss:
        toss2 = 0
        return user+" won the toss!"
    else:
        toss2 = 1
        return "Computer won the toss!"

def comp_batting1():
    global comp_score
    comp_score = 0
    count = 0
    print("-----------------------------COMPUTER BATTING----------------------------")
    while count == 0:
        comp_run1 = random.randint(1,6)
        user_bowl1 = int(input("Enter a number between 1 and 6: "))
        while user_bowl1 < 1 or user_bowl1 > 6:
            user_bowl1 = int(input("Enter a valid number: "))
        print("computer number: ",comp_run1)
        print("user number: ",user_bowl1)
        if user_bowl1 == comp_run1:
            count = 1
            print("computer out!\n")
        else:
            comp_score = comp_score + comp_run1
            print("score: ",comp_score,"\n")
    return "Computer Final Score: "+str(comp_score)

def comp_batting2():
    global comp_score
    comp_score = 0
    count = 0
    print("-----------------------------COMPUTER BATTING----------------------------")
    while count == 0 and comp_score <= user_score:
        comp_run2 = random.randint(1,6)
        user_bowl2 = int(input("Enter a number between 1 and 6: "))
        while user_bowl2 < 1 or user_bowl2 > 6:
            user_bowl2 = int(input("Enter a valid number: "))
        print("computer number: ",comp_run2)
        print("user number: ",user_bowl2)
        if user_bowl2 == comp_run2:
            count = 1
            print("Computer out!")
        else:
            comp_score = comp_score + comp_run2
            print("score: ",comp_score)
            if comp_score<=user_score:
                print("computer need "+ str(user_score-comp_score+1)+" more to win\n")
    return "\nComputer Final Score: "+str(comp_score)

def user_batting1():
    global user_score
    user_score = 0
    count = 0
    print("-----------------------------"+user+" BATTING----------------------------")
    while count == 0:
        comp_bowl1 = random.randint(1,6)
        user_run1 = int(input("Enter a number between 1 and 6: "))
        while user_run1 < 1 or user_run1 > 6:
            user_run1 = int(input("Enter a valid number: "))
        print("computer number: ",comp_bowl1)
        print("your number: ",user_run1)
        if user_run1 == comp_bowl1:
            count = 1
            print(user+" out!\n")
        else:
            user_score = user_score + user_run1
            print("score: ",user_score,"\n")
    return user+" Final Score: "+str(user_score)

def user_batting2():
    global user_score
    user_score = 0
    count = 0
    print("-----------------------------"+user+" BATTING----------------------------")
    while count == 0 and user_score <= comp_score:
        comp_bowl2 = random.randint(1,6)
        user_run2 = int(input("Enter a number between 1 and 6: "))
        while user_run2 < 1 or user_run2 > 6:
            user_run2 = int(input("Enter a valid number: "))
        print("computer number: ",comp_bowl2)
        print("your number: ",user_run2)
        if user_run2 == comp_bowl2:
            count = 1
            print(user+" out!")
        else:
            user_score = user_score + user_run2
            print("score: ",user_score)
            if user_score<=comp_score:
                print(user+" need "+str(comp_score-user_score+1)+" more to win\n")
    return "\n"+user+" Final Score: "+str(user_score)

while True:
    print("------------------Welcome to the game of DIGITAL CRICKET-----------------\n")
    print("Rules for the game are as follows:-\n"
    , "1) User have to enter any number between 1 and 6 and it will be compared with the number randomly generated by the computer.\n"
    , "2) If both the numbers match then batsman will be considered out.\n"
    , "3) If the number doesn't match then the number which batsman has presented will be added to it's final score.")
    print("-------------------------------------------------------------------------")
    user = input("ENTER YOUR NAME: ")
    print("--------------------------------TOSS TIME--------------------------------")
   
    toss1 = int(input("Enter your toss(0/1): "))
    while toss1 < 0 or toss1 > 1:
        toss1 = int(input("Enter valid choice: "))
    print(toss(toss1))
   
    if toss2 == 0:
        print("Enter your choice: \n", "1. BAT(1)\n", "2. BOWL(2)")
        user_choice = int(input())
        while user_choice < 1 or user_choice > 2:
            user_choice = int(input("Enter valid choice: "))
        if user_choice == 1:
            print("---------------------->"+user+" chose to bat first<----------------------\n")
            print(user_batting1())
            print(comp_batting2())
        else:
            print("---------------------->"+user+" chose to bowl first<----------------------\n")
            print(comp_batting1())
            print(user_batting2())
   
    else:
        comp_choice = random.randint(1,2)
        if comp_choice == 1:
            print("---------------------->Computer chose to bat first<----------------------\n")
            print(comp_batting1())
            print(user_batting2())
        else:
            print("---------------------->Computer chose to bowl first<---------------------\n")
            print(user_batting1())
            print(comp_batting2())
   
    if user_score > comp_score:
        print("========================>"+user+" won the match!<========================")
    elif user_score == comp_score:
        print("==============================>Match Tied!<==============================")
    else:
        print("=========================>Computer Won the match<========================")
   
    print("Do you want to play again! \n", "1. Yes(1)\n", "2. No(2)")
    again = int(input())
    while again < 1 or again > 2:
        again = int(input("Enter valid choice: "))
    if again == 2:
        break